# Example content of the other .yml file (e.g., firebase-hosting-main.yml)
name: Deploy to Firebase Hosting on push
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # ... other steps
      # - name: Run build # <-- COMMENTED OUT ENTIRE STEP OR JUST THE LINE BELOW
      #   run: npm ci && npm run build # <-- THIS LINE SHOULD BE COMMENTED OUT
      # ... other steps
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MYTASKTRACKERSYNC }}
          projectId: mytasktrackersync